List_Belanjaan/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_Item, show_xml, show_json, show_json_by_id, show_xml_by_id, register, login_user, logout_user, tambah_amount, kurang_amount, hapus_item, get_product_json,add_product_ajax, hapus_item_ajax, tambah_amount_ajax, kurang_amount_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_Item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('tambah_amount/<int:id>/', tambah_amount, name='tambah_amount'),
    path('kurang_amount/<int:id>/', kurang_amount, name='kurang_amount'),
    path('hapus_item/<int:id>/', hapus_item, name='hapus_item'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('hapus_item_ajax/<int:id>/', hapus_item, name='hapus_item'),
    path('kurang_amount_ajax/<int:id>/', get_product_json, name='get_product_json'),
    path('tambah_amount_ajax/<int:id>', add_product_ajax, name='add_product_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    amount = models.IntegerField()
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add= True)

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "price", "amount", "description"]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.core import serializers
from main.forms import ItemForm, Item
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages 
from django.contrib.auth import authenticate, login 
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.http import JsonResponse
import json
from django.contrib.auth import logout as auth_logout

# Create your views here.

# def show_item()
@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user = request.user)
    context = {
        'name': request.user.username, 
        'items': items,
        'last_login': request.COOKIES['last_login'],
        'pembuat' : 'Tsabit Coda R - PBP C'
    }

    return render(request, "main.html", context)

def create_Item(request):
    # message = ''
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_Item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request,id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Welcome Gamers! Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.date.today()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

@csrf_exempt
def kurang_amount(request,id):
    barang_check = Item.objects.get(pk=id)
    if barang_check.amount > 1:
        barang_check.amount -= 1
        barang_check.save()
    else:
        barang_check.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def tambah_amount(request,id):
    barang_check = Item.objects.get(pk=id)
    barang_check.amount += 1
    barang_check.save()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def hapus_item(request,id):
    barang_check = Item.objects.get(pk=id)
    barang_check.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

def get_product_json(request):
    data = Item.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize('json', data))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        amount = request.POST.get("amount")
        user = request.user

        new_product = Item(name=name, price=price, description=description,amount=amount, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def kurang_amount_ajax(request,id):
    barang_check = Item.objects.get(pk=id)
    if barang_check.amount > 1:
        barang_check.amount -= 1
        barang_check.save()
        return HttpResponse(b"CREATED", status=201)
    else:
        barang_check.delete()
    # return HttpResponseRedirect(reverse('main:show_main'))
    return HttpResponse(b"NOT CREATED", status=201)

@csrf_exempt
def tambah_amount_ajax(request,id):
    barang_check = Item.objects.get(pk=id)
    barang_check.amount += 1
    barang_check.save()
    # return HttpResponseRedirect(reverse('main:show_main'))
    return HttpResponse(b"ADD", status=201)

@csrf_exempt
def hapus_item_ajax(request,id):
    barang_check = Item.objects.get(pk=id)
    barang_check.delete()
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            amount = int(data["amount"]),
            description = data["description"],
            # date_added = data(["date_added"])
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Item"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    hehehehehe
</body>
</html>

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    .btn {
        /* background-color: white; */
        /* border: rgb(194, 35, 35); */
        color: #ff4500;
        /* padding: 20px; */
        text-align: center;
        text-decoration: none;
        display: inline-block;
        /* font-size: 16px; */
        /* margin: 4px 2px; */
        cursor: pointer;
        width: 170px;
    }

    .login{
        justify-content: center;
        /* display: flex; */
        flex-direction: column;
        display: flex;
        height: 80vh;
        align-items: center
    }

</style>


<div class = "login" href ="static/styling-login.css">

    <h1 style="color: #ff4500" height="100%"><center>USER LOGIN</center></h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table style="border:2px solid whitesmoke;margin-left:auto;margin-right:auto;;padding: 10px; border-radius: 10px;">
            <tr>
                <td style="color: rgb(89, 31, 31);">Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td style="color: rgb(89, 31, 31);">Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
            {% for message in messages %}
                <center>{{ message }}</center>
            {% endfor %}
    {% endif %}     
        
   <center style="color: aliceblue;">Don't have an account yet? <a href="{% url 'main:register' %}">JOIN US NOW!</a></center> 

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <h1 style="color: rgb(238, 225, 209);">Welcome to Coda Shop !</h1>

   <h5 style="color: rgb(238, 225, 209);">Hi,  {{name}}</h5>

    <p style="color: rgb(238, 225, 209);">{{ pembuat }}<p>

    <div class="bordered-table" id="product_table"></div>

    {% comment %} Berikut cara memperlihatkan data produk di bawah baris ini {% endcomment %}

<br />

<a href="{% url 'main:create_item' %}">
    <button class="buttonakhir">
        Add New Item !!
    </button>
</a>

<a href="{% url 'main:logout' %}">
    <button class="buttonakhir">
        Logout
    </button>
</a>

<h5 style="color: rgb(238, 225, 209);">Latest Login: {{ last_login }}</h5>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="col-form-label">Name:</label>
                        <input type="text" class="form-control" id="name" name="name"></input>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Price:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Amount:</label>
                        <textarea class="form-control" id="amount" name="amount"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
            </div>
        </div>
    </div>
</div>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>







<script>
    async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
    }
    async function refreshProducts() {
        document.getElementById("product_table").innerHTML = ""
        const products = await getProducts()
        let htmlString = ``
        products.forEach((item) => {
            htmlString += `    <div class="col-md-1"></div>
      <div class="card rounded" style="width: 20rem;">
        <div class="card-body">
          <h3 class="card-title" style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">${item.fields.name}</h5>
          <h3 class="card-subtitle mb-2 text-muted">${item.fields.price} $</h6>
          <p class="card-text">${item.fields.description}</p>
          <p class ="card-text" style="background-color: antiquewhite;">Stock : ${item.fields.amount}</p>
          <button class="btn btn-primary" onclick="tambah_amount_ajax(${item.pk})">+</button>
          <button class="btn btn-primary" onclick="kurang_amount_ajax(${item.pk})">-</button>
          <button class="btn btn-primary" onclick="hapus_item_ajax(${item.pk})">DELETE</button>
        </div>
      </div>` 
        })
        
        document.getElementById("product_table").innerHTML = htmlString
    }

    refreshProducts()

    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: 'POST',
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    function tambah_amount_ajax(id) {
        fetch('/tambah_amount_ajax/0/'.replace("0", id), {
            method: 'POST',
        }).then(refreshProducts)

        return false
    }

    function kurang_amount_ajax(id) {
        fetch('/kurang_amount_ajax/0/'.replace("0", id), {
            method: 'POST',
        }).then(refreshProducts)

        return false
    }

    function hapus_item_ajax(id) {
        fetch('/hapus_item_ajax/0/'.replace("0", id), {
            method: 'DELETE',
        }).then(refreshProducts)
    }
    document.getElementById("button_add").onclick = addProduct

</script>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login" style="background-color: aliceblue;">
    
    <h1>Register</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}